spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    driverClassName: org.postgresql.Driver
    username: library
    password: library
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  # JPA properties
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true