version: '3'

services:
  postgres:
    image: "postgres:9.6-alpine"
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_SERVER=postgres
      - POSTGRES_DB=library
      - POSTGRES_USER=library
      - POSTGRES_PASSWORD=library
  ms-launcher:
   container_name: ms-launcher
   restart: always
   build:
     context: ./ms-launcher/
   ports:
     - "8080:8080"
   depends_on:
     - postgres
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/library
     - SPRING_DATASOURCE_USERNAME=library
     - SPRING_DATASOURCE_PASSWORD=library
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  frontend:
   container_name: frontend
   build:
     context: ./police-assurance-frontend/
   ports:
     - "3000:3000"
   links:
     - ms-launcher
   